K22CNT4_NguyenVanQuyet_Project2/K22CNT4_NguyenVanQuyet_Project2/Controllers/NVQ_San_PhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT4_NguyenVanQuyet_Project2.Models;

namespace K22CNT4_NguyenVanQuyet_Project2.Controllers
{
    public class NVQ_San_PhamController : Controller
    {
        private NVQDbEntities db = new NVQDbEntities();

        // GET: NVQ_San_Pham
        public ActionResult Index()
        {
            var san_Pham = db.San_Pham.Include(s => s.Hang_San_Xuat);
            return View(san_Pham.ToList());
        }

        // GET: NVQ_San_Pham/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            San_Pham san_Pham = db.San_Pham.Find(id);
            if (san_Pham == null)
            {
                return HttpNotFound();
            }
            return View(san_Pham);
        }

        // GET: NVQ_San_Pham/Create
        public ActionResult Create()
        {
            ViewBag.id_hang = new SelectList(db.Hang_San_Xuat, "id_hang", "ten_hang");
            return View();
        }

        // POST: NVQ_San_Pham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_sp,ten_sp,id_hang,mo_ta,gia,so_luong_ton,ngay_tao")] San_Pham san_Pham)
        {
            if (ModelState.IsValid)
            {
                db.San_Pham.Add(san_Pham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_hang = new SelectList(db.Hang_San_Xuat, "id_hang", "ten_hang", san_Pham.id_hang);
            return View(san_Pham);
        }

        // GET: NVQ_San_Pham/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            San_Pham san_Pham = db.San_Pham.Find(id);
            if (san_Pham == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_hang = new SelectList(db.Hang_San_Xuat, "id_hang", "ten_hang", san_Pham.id_hang);
            return View(san_Pham);
        }

        // POST: NVQ_San_Pham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_sp,ten_sp,id_hang,mo_ta,gia,so_luong_ton,ngay_tao")] San_Pham san_Pham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(san_Pham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_hang = new SelectList(db.Hang_San_Xuat, "id_hang", "ten_hang", san_Pham.id_hang);
            return View(san_Pham);
        }

        // GET: NVQ_San_Pham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            San_Pham san_Pham = db.San_Pham.Find(id);
            if (san_Pham == null)
            {
                return HttpNotFound();
            }
            return View(san_Pham);
        }

        // POST: NVQ_San_Pham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            San_Pham san_Pham = db.San_Pham.Find(id);
            db.San_Pham.Remove(san_Pham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

K22CNT4_NguyenVanQuyet_Project2/K22CNT4_NguyenVanQuyet_Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - K22CNT4 - Nguyễn Văn Quyết - Project2 </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nguyễn Văn Quyết", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Loại sản phẩm", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sản phẩm", "Index", "NVQ_San_Pham", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Giỏ hàng", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <div class="d-flex mx-2">
                    <a href=" #" class="btn btn-primary mx-1">Đăng Ký</a>
                    <a href=" #" class="btn btn-success">Đăng Nhập</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>